import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import { VisualEditing } from 'next-sanity';
import NavBar from '@/components/Navbar';
import { ButtonLink } from '@/components/Link';
import { draftMode } from 'next/headers';
import { generateStyles, getSettings } from '@/functions/loaders/settings';
// import { sanityFetch } from '@/sanity/lib/fetch.server';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: {
    default: "Template blog",
    template: `| %s`
  },
  description: 'Generated by create next app',
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const settings = await getSettings();
  let styles = '';

  if (settings.colors) {
    styles = generateStyles(settings.colors);
    console.log("styles", styles)
  }

  return (
    <html lang="en">

      <body className={inter.className}>
        <NavBar>
          {draftMode().isEnabled && (
            //   <div className='w-fit py-2.5 px-1'>
            <ButtonLink href="/api/disable-draft">
              Disable preview mode
            </ButtonLink>
            //   </div>
          )}
        </NavBar>
        <main>{children}</main>
        {draftMode().isEnabled && <VisualEditing />}
        <style>
          {`:root { ${styles} }`}
        </style>
      </body>
    </html>
  );
}
